dist: xenial
language: go

go:
  - 1.x

sudo: false

git:
  depth: 10

branches:
  only:
    - sources

install:
  -  npm install -g postcss-cli
  # Hugo - documentation
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - make hugo-build

deploy:
  - provider: pages
    target_branch: master
    local_dir: public
    edge: true
    skip_cleanup: true
    github_token: ${GITHUB_TOKEN}
    on:
      branch: sources
