baseURL = "https://ldez.github.io/"
title = "The Best Code is No Code At All"
languageCode = "en-us"
#theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# DefaultContentLanguage = "en"

googleAnalytics = "UA-62168601-1"
disqusShortname = "thebestcodeisnocodeatall"

[permalinks]
  article = "/blog/:year/:month/:day/:slug/"
  audio = "/blog/:year/:month/:day/:slug/"
  code = "/blog/:year/:month/:day/:slug/"
  gallery = "/blog/:year/:month/:day/:slug/"
  link = "/blog/:year/:month/:day/:slug/"
  page = "/blog/:year/:month/:day/:slug/"
  quote = "/blog/:year/:month/:day/:slug/"
  video = "/blog/:year/:month/:day/:slug/"

[params]
  favicon = "" # set a favicon icon
  subtitle = "A blog with code inside."

  enableLightDarkTheme = true

  siteWidth = "1000px"
  permanentTopNav = true
  # showHeaderLanguageChooser = false

  # Description and metadata for the search engines
  author = "ldez"
  description = "ldez blog"
  keywords = "blog,golang,go,software,programming,developer"

  # if you want to use gravatar for the header image
  gravatarEMail = "lfernandez.dev@gmail.com"

  # social media profile urls for the footer links
  showSocialMedia = true
  socialMediaLinks = [
    { link = "https://bento.me/ldez", icon = "fas fa-user"},
    { link = "https://github.com/ldez", icon = "fab fa-github" },
    { link = "https://fosstodon.org/@ldez", icon = "fab fa-mastodon", rel = "me" },
    { link = "https://bsky.app/profile/ldezoss.bsky.social", icon = "fab fa-bluesky"},
    { link = "https://twitter.com/ludnadez", icon = "fab fa-twitter"},
  ]

  copyrightBy = "by ldez"
  copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
  copyrightYearOverride = "2024"
  copyrightUrl = "https://github.com/ldez"
  creditsText = "Bilberry Hugo Theme"
  creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"

[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]

[module]
  [[module.imports]]
  path = "github.com/Lednerb/bilberry-hugo-theme/v4"
